// Переклад на різні мови
const translations = {
  ua: {
    home: "Головна",
    create: "Почати творити",
    team: "Команда",
    services: "Послуги",
    contacts: "Контакти",
    heroTitle: "Створюємо кімнати",
    heroSpan: "мрій",
    heroSubtitle: "RoomCraft - це простий 2D редактор для планування та дизайну кімнат. Створюйте макети, розставляйте меблі та експериментуйте з плануванням простору.",
    heroButton: "Почати проєкт",
    createTitle: "Почніть творити вже сьогодні",
    createSubtitle: "Простий 2D редактор для планування кімнат. Створюйте, редагуйте та експериментуйте з дизайном.",
    createFirstTitle: "1. Створіть план",
    createFirstSubtitle: "Редагуйте контур кімнати, додайте стіни, двері та вікна за допомогою простих інструментів",
    createFirstButton: "Почати планування",
    createSecondTitle: "2. Додайте меблі",
    createSecondSubtitle: "Перетягуйте меблі з бібліотеки об'єктів: дивани, столи, ліжка та інші предмети інтер'єру.",
    createSecondButton: "Переглянути меблі",
    createThirdTitle: "3. Збережіть проект",
    createThirdSubtitle: "Зберігайте свої проекти, та насолоджуйтеся планом, використовуйте в своїх цілях",
    createThirdButton: "Спробувати редактор",
    abilityTitle: "Можливості редактора",
    abilitySubtitle: "Все необхідне для створення планів кімнат та експериментів з дизайном",
    abilityFirstTitle: "Планування кімнат",
    abilityFirstSubtitle: "Створюйте плани кімнат будь-якої форми з точними розмірами та пропорціями.",
    abilityFirstResult: "Безкоштовно",
    abilitySecondTitle: "Бібліотека меблів",
    abilitySecondSubtitle: "Велика колекція 2D об'єктів: меблі, техніка, декор та інші елементи.",
    abilitySecondResult: "17+ об'єктів",
    abilityThirdTitle: "Кольори та текстури",
    abilityThirdSubtitle: "Налаштовуйте кольори стін, підлоги та меблів для кращої візуалізації.",
    abilityThirdResult: "Необмежено",
    abilityFourthTitle: "Збереження проектів",
    abilityFourthSubtitle: "Зберігайте свої проекти в хмарі та працюйте з будь-якого пристрою.",
    abilityFourthtResult: "Синхронізація",
      contactTitle: "Наші контакти",
    contactTel: "Телефон",
    contactEmail: "Email",
    contactMessage: "Надішліть повідомлення",
    contactName: "Ім'я *",
    contactEmailLabel: "Email *",
    contactPhoneLabel: "Телефон",
    contactMessageLabel: "Повідомлення *",
    contactSendBtn: "Надіслати повідомлення",
    teamTitle: "Наша команда",
  teamLeciv: "Лесів Павло",
  teamFrontend: "Frontend розробник",
  teamLecivText: "Відповідає за основну сторінку на якій ви це читаєте",
  teamLev: "Лев Деревянчук",
  teamLevText: "Відповідає за організаційні питання і за мови",
  teamTumur: "Тимур Катснельсон",
  teamTumurText: "Розробляє самий редактор в якому будуть всі працювати і збереження проектів",
    footerSubtitle: "Простий та зручний 2D редактор для планування кімнат. Створено з любов'ю до Хакатону GoITeens 2025.",
  footerEdit: "Редактор",
  footerStart: "Почати роботу",
  footerLibrary: "Бібліотека меблів",
  footerInstruction: "Інструкції",
  footerContact: "Контакти",
  footerreserve: "© 2025 RoomCraft. Всі права захищені.",
  },
  en: {
    home: "Home",
    create: "Start Creating",
    team: "Team",
    services: "Services",
    contacts: "Contacts",
    heroTitle: "Design your dream",
    heroSpan: "room",
    heroSubtitle: "RoomCraft is a simple 2D editor for planning and designing rooms. Create layouts, arrange furniture, and experiment with room setups.",
    heroButton: "Start project",
    createTitle: "Start creating today",
    createSubtitle: "A simple 2D room planner. Create, edit, and experiment with your design.",
    createFirstTitle: "1. Create a plan",
    createFirstSubtitle: "Edit the room outline, add walls, doors and windows using simple tools",
    createFirstButton: "Start planning",
    createSecondTitle: "2. Add furniture",
    createSecondSubtitle: "Drag and drop furniture from the object library: sofas, tables, beds, and more.",
    createSecondButton: "Browse furniture",
    createThirdTitle: "3. Save your project",
    createThirdSubtitle: "Save your layouts and enjoy your plan — use it however you need",
    createThirdButton: "Try the editor",
    abilityTitle: "Editor Features",
    abilitySubtitle: "Everything you need to create room layouts and experiment with design",
    abilityFirstTitle: "Room Planning",
    abilityFirstSubtitle: "Create rooms of any shape with precise dimensions and proportions.",
    abilityFirstResult: "Free",
    abilitySecondTitle: "Furniture Library",
    abilitySecondSubtitle: "Large collection of 2D objects: furniture, appliances, decor, and more.",
    abilitySecondResult: "17+ items",
    abilityThirdTitle: "Colors & Textures",
    abilityThirdSubtitle: "Customize wall, floor, and furniture colors for better visualization.",
    abilityThirdResult: "Unlimited",
    abilityFourthTitle: "Project Saving",
    abilityFourthSubtitle: "Save your projects in the cloud and work from any device.",
    abilityFourthtResult: "Sync enabled",
    contactTitle: "Contact Us",
    contactTel: "Phone",
    contactEmail: "Email",
    contactMessage: "Send a Message",
    contactName: "Name *",
    contactEmailLabel: "Email *",
    contactPhoneLabel: "Phone",
    contactMessageLabel: "Message *",
    contactSendBtn: "Send Message",
      teamTitle: "Our Team",
  teamLeciv: "Pavlo Lesiv",
  teamFrontend: "Frontend Developer",
  teamLecivText: "Responsible for the main page you are currently reading.",
  teamLev: "Lev Derevyanchuk",
  teamLevText: "Handles organizational tasks and languages.",
  teamTumur: "Timur Katsnelson",
  teamTumurText: "Develops the core editor where users work and save projects.",
    footerSubtitle: "A simple and user-friendly 2D editor for room planning. Created with love for the GoITeens 2025 Hackathon.",
  footerEdit: "Editor",
  footerStart: "Get Started",
  footerLibrary: "Furniture Library",
  footerInstruction: "Instructions",
  footerContact: "Contacts",
  footerreserve: "© 2025 RoomCraft. All rights reserved.",
  },
  de: {
    home: "Heim",
    create: "Beginnen Sie mit dem Erstellen",
    team: "Team",
    services: "Dienstleistungen",
    contacts: "Kontakte",
    heroTitle: "Gestalte dein",
    heroSpan: "Traumzimmer",
    heroSubtitle: "RoomCraft ist ein einfacher 2D-Editor zur Planung und Gestaltung von Räumen. Erstelle Layouts, platziere Möbel und experimentiere mit der Raumaufteilung.",
    heroButton: "Projekt starten",
    createTitle: "Beginnen Sie noch heute mit der Gestaltung",
    createSubtitle: "Ein einfacher 2D-Raumplaner. Erstellen, bearbeiten und experimentieren Sie mit dem Design.",
    createFirstTitle: "1. Plan erstellen",
    createFirstSubtitle: "Bearbeiten Sie den Raumumriss, fügen Sie Wände, Türen und Fenster mit einfachen Werkzeugen hinzu",
    createFirstButton: "Planung starten",
    createSecondTitle: "2. Möbel hinzufügen",
    createSecondSubtitle: "Ziehen Sie Möbel aus der Objektbibliothek: Sofas, Tische, Betten und mehr.",
    createSecondButton: "Möbel durchsuchen",
    createThirdTitle: "3. Projekt speichern",
    createThirdSubtitle: "Speichern Sie Ihre Entwürfe und nutzen Sie den Plan für Ihre Zwecke",
    createThirdButton: "Editor ausprobieren",
    abilityTitle: "Editor-Funktionen",
    abilitySubtitle: "Alles, was Sie für die Raumplanung und Gestaltung benötigen",
    abilityFirstTitle: "Raumplanung",
    abilityFirstSubtitle: "Erstellen Sie Räume jeder Form mit genauen Maßen und Proportionen.",
    abilityFirstResult: "Kostenlos",
    abilitySecondTitle: "Möbelbibliothek",
    abilitySecondSubtitle: "Große Sammlung von 2D-Objekten: Möbel, Geräte, Dekor und mehr.",
    abilitySecondResult: "17+ Objekte",
    abilityThirdTitle: "Farben & Texturen",
    abilityThirdSubtitle: "Passen Sie Wand-, Boden- und Möbelfarben für eine bessere Visualisierung an.",
    abilityThirdResult: "Unbegrenzt",
    abilityFourthTitle: "Projektspeicherung",
    abilityFourthSubtitle: "Speichern Sie Ihre Projekte in der Cloud und arbeiten Sie von überall.",
    abilityFourthtResult: "Synchronisierung",
    contactTitle: "Unsere Kontakte",
    contactTel: "Telefon",
    contactEmail: "E-Mail",
    contactMessage: "Nachricht senden",
    contactName: "Name *",
    contactEmailLabel: "E-Mail *",
    contactPhoneLabel: "Telefon",
    contactMessageLabel: "Nachricht *",
    contactSendBtn: "Nachricht senden",
      teamTitle: "Unser Team",
  teamLeciv: "Pavlo Lesiv",
  teamFrontend: "Frontend-Entwickler",
  teamLecivText: "Verantwortlich für die Hauptseite, auf der Sie gerade lesen.",
  teamLev: "Lev Derevyanchuk",
  teamLevText: "Verantwortlich für organisatorische Aufgaben und Sprachen.",
  teamTumur: "Timur Katsnelson",
  teamTumurText: "Entwickelt den Editor, in dem alle arbeiten und Projekte gespeichert werden.",
    footerSubtitle: "Ein einfacher und benutzerfreundlicher 2D-Editor für Raumplanung. Mit Liebe für den GoITeens 2025 Hackathon erstellt.",
  footerEdit: "Editor",
  footerStart: "Erste Schritte",
  footerLibrary: "Möbelbibliothek",
  footerInstruction: "Anleitungen",
  footerContact: "Kontakte",
  footerreserve: "© 2025 RoomCraft. Alle Rechte vorbehalten.",
  }
};


  const langSelector = document.getElementById("selectionLanguage");
  langSelector.addEventListener("change", (e) => {
    const selectedLang = e.target.value;
    const elements = document.querySelectorAll("[data-name]");

    elements.forEach((el) => {
      const key = el.getAttribute("data-name");
      el.textContent = translations[selectedLang][key];
    });

    // Зберегти мову в localStorage
    localStorage.setItem("selectedLanguage", selectedLang);
  });

  // Автозавантаження мови при оновленні сторінки
  window.addEventListener("DOMContentLoaded", () => {
    const savedLang = localStorage.getItem("selectedLanguage") || "ua";
    langSelector.value = savedLang;
    langSelector.dispatchEvent(new Event("change"));
  });

  // Бурер меню
    const burger = document.getElementById("burger");
  const nav = document.querySelector(".header-nav");

  burger.addEventListener("click", () => {
    burger.classList.toggle("active");
    nav.classList.toggle("open");
  });